### PR TITLE
Assure there is always a default dashboard.

### LINKED ISSUE #9: No default dashboard
If no dashboard exists, adding a widget fails.

Solution 1: Automatically add a dashboard

Solution 2: Disable add button until a dashboard is loaded

### LINKED ISSUE #26: Deleting the currently used dashboard crashed app
Deleting the currently used dashboard results in an error on page refresh:
```
main.js:210 
Uncaught TypeError: Cannot read property 'name' of undefined
    at activateDashboard (main.js:210)
    at init (main.js:339)
    at main.js:346
```

### PR DESCRIPTION
**Pull request by EggiJan**
Fixes #9, fixes #26

### CODE REVIEW

File: main.js [hunk 1]
```diff
@@ -158,6 +162,11 @@ function saveDashboard() {
 function loadDashboards() {
   console.log('Load Dashboards');
   var dashboards = storageService.dashboards.getAll();
+  if(Object.keys(dashboards).length == 0) {
```
Comment (EggiJan) [inline main.js]: Please use `===` here
